#!/usr/bin/env bash
set -euo pipefail

# Build script for Chrome extension
# Generates manifest.json and config.js based on environment (dev or prod)

ENV="${1:-dev}"

if [[ "$ENV" != "dev" && "$ENV" != "prod" ]]; then
  echo "Usage: $0 [dev|prod]"
  echo "  dev  - Development mode (includes localhost in host_permissions)"
  echo "  prod - Production mode (removes localhost from host_permissions)"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_MANIFEST="${SCRIPT_DIR}/manifest.${ENV}.json"
TARGET_MANIFEST="${SCRIPT_DIR}/manifest.json"

if [[ ! -f "$SOURCE_MANIFEST" ]]; then
  echo "Error: Source manifest not found at $SOURCE_MANIFEST"
  exit 1
fi

echo "Building extension for environment: $ENV"

# 1. Copy the appropriate manifest
cp "$SOURCE_MANIFEST" "$TARGET_MANIFEST"
echo "Manifest copied: manifest.${ENV}.json -> manifest.json"

# 2. Generate config.js with environment flag
IS_PRODUCTION=$([[ "$ENV" == "prod" ]] && echo "true" || echo "false")
cat > "${SCRIPT_DIR}/config.js" <<EOF
// Auto-generated by build.sh — DO NOT EDIT MANUALLY
// Run: ./build.sh [dev|prod]
export const IS_PRODUCTION = ${IS_PRODUCTION};
EOF
echo "Config generated: config.js (IS_PRODUCTION=${IS_PRODUCTION})"

echo "Extension is ready for $ENV environment."
